In [1]:
import pandas as pd
import re

## Importing Data

In [2]:
imports_df = pd.read_csv('../data/census_imports.csv')
exports_df = pd.read_csv('../data/census_exports.csv')
gdp_df = pd.read_csv('../data/gdp_industry.csv')

In [3]:
imports_df = imports_df[imports_df['time'].str.contains(r'(\d{4})-(12)')]
imports_df['YEAR'] = imports_df['time'].str.extract(r'(\d{4})-12')

exports_df = exports_df[exports_df['time'].str.contains(r'(\d{4})-(12)')]
exports_df['YEAR'] = exports_df['time'].str.extract(r'(\d{4})-12')

/var/folders/6q/62m63jt13_79jxp668tbwsd80000gp/T/ipykernel_86112/3826823084.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  imports_df = imports_df[imports_df['time'].str.contains(r'(\d{4})-(12)')]
/var/folders/6q/62m63jt13_79jxp668tbwsd80000gp/T/ipykernel_86112/3826823084.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  exports_df = exports_df[exports_df['time'].str.contains(r'(\d{4})-(12)')]

In [4]:
imports_df = imports_df.drop(columns='time')
imports_df.columns = ['STATE','VALUE','NAICS','NAICS_LDESC','YEAR']

exports_df = exports_df.drop(columns='time')
exports_df.columns = ['STATE','VALUE','NAICS','NAICS_LDESC','YEAR']

## Cleaning and Transforming GDP by Capita

In [5]:
gdp_df = gdp_df.drop(columns=['Region','TableName','LineCode','Unit',
                     '1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009'])

gdp_df = gdp_df.rename(columns={'GeoName':'STATE/REGION','IndustryClassification':'NAICS','Description':'NAICS_LDESC'})

In [6]:
state_abbr = { 'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 
               'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 
               'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 
               'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS', 'Kentucky': 'KY', 
               'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT', 
               'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 
               'Ohio': 'OH', 'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD', 
               'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY' }

In [7]:
gdp_df['STATE/REGION'] = gdp_df['STATE/REGION'].replace('United States *','USA').replace(state_abbr)

gdp_df['NAICS_LDESC'] = gdp_df['NAICS_LDESC'].str.strip()

In [8]:
gdp_df.head(5)

,GeoFIPS,STATE/REGION,NAICS,NAICS_LDESC,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,0,USA,...,All industry total,15048971,15599732,16253970,16880683,17608138,18295019,18804913,19612102,20656516,21539982.0,21375281,23725645,26054614,27811517,29298013,30762099
1,0,USA,...,Private industries,12939469,13461114,14092708,14665532,15332504,15951002,16413054,17156255,18097765,18909779.0,18663991,20917717,23128892,24712793,26001672,27315089
2,0,USA,11,"Agriculture, forestry, fishing and hunting",145743,179887,179457,215847,200581,182147,167492,176840,177117,164214.0,164383,230723,294048,270441,269686,272014
3,0,USA,111-112,Farms,117043,151135,148752,184472,167051,146259,130270,138733,136825,122630.0,120506,185707,247070,218198,215830,(NA)
4,0,USA,113-115,"Forestry, fishing, and related activities",28700,28752,30705,31375,33530,35887,37222,38107,40291,41585.0,43877,45016,46978,52243,53856,(NA)

In [9]:
gdp_df['NAICS'].unique()

array(['...', '11', '111-112', '113-115', '21', '211', '212', '213', '22',
       '23', '31-33', '321,327-339', '321', '327', '331', '332', '333',
       '334', '335', '3361-3363', '3364-3466,3369', '337', '339',
       '311-316,322-326', '311-312', '313-314', '315-316', '322', '323',
       '324', '325', '326', '42', '44-45', '48-49', '481', '482', '483',
       '484', '485', '486', '487-488,492', '493', '51', '511', '512',
       '515517', '518-519', '52,53', '52', '521-522', '523', '524', '525',
       '53', '531', '532-533', '54,55,56', '54', '5411', '5415',
       '5412-5414,5416-5419', '55', '56', '561', '562', '61,62', '61',
       '62', '621', '622', '623', '624', '71,72', '71', '711-712', '713',
       '72', '721', '722', '81', '92', '11,21', '42,44-45', '22,48-49',
       '31-33,51'], dtype=object)

In [10]:
gdp_df['NAICS'] = gdp_df['NAICS'].replace('515517','515-517')

In [11]:
summary_desc = gdp_df.loc[gdp_df['NAICS'] == '...','NAICS_LDESC'].unique().tolist()
summ_codemap = {desc: f'..{i}' for i, desc in enumerate(summary_desc)}

In [12]:
gdp_df.loc[gdp_df['NAICS'].str.contains(r'\.\.',regex=True), 'NAICS'] = gdp_df.loc[gdp_df['NAICS'].str.contains(r'\.\.',regex=True), 'NAICS_LDESC'].map(summ_codemap)

In [13]:
gdp_df.loc[gdp_df['NAICS'].str.contains(',')]['NAICS'].unique()

array(['321,327-339', '3364-3466,3369', '311-316,322-326', '487-488,492',
       '52,53', '54,55,56', '5412-5414,5416-5419', '61,62', '71,72',
       '11,21', '42,44-45', '22,48-49', '31-33,51'], dtype=object)

In [14]:
# Variables to identify whether aggregate codes are exclusive (groups without other given rows) 
#                                               or inclusive (groupings from BEA)
excl_groups = ['3364-3466,3369','487-488,492','5412-5414,5416-5419']
incl_groups = ['311-316,322-326','321,327-339','52,53','54,55,56','61,62','71,72','11,21','42,44-45','22,48-49','31-33,51']

gdp_df['BEA_GROUP'] = gdp_df['NAICS'].isin(incl_groups)

In [15]:
gdp_codes = gdp_df['NAICS'].unique().tolist()

In [16]:
gdp_codes

['..0',
 '..1',
 '11',
 '111-112',
 '113-115',
 '21',
 '211',
 '212',
 '213',
 '22',
 '23',
 '31-33',
 '321,327-339',
 '321',
 '327',
 '331',
 '332',
 '333',
 '334',
 '335',
 '3361-3363',
 '3364-3466,3369',
 '337',
 '339',
 '311-316,322-326',
 '311-312',
 '313-314',
 '315-316',
 '322',
 '323',
 '324',
 '325',
 '326',
 '42',
 '44-45',
 '48-49',
 '481',
 '482',
 '483',
 '484',
 '485',
 '486',
 '487-488,492',
 '493',
 '51',
 '511',
 '512',
 '515-517',
 '518-519',
 '52,53',
 '52',
 '521-522',
 '523',
 '524',
 '525',
 '53',
 '531',
 '532-533',
 '54,55,56',
 '54',
 '5411',
 '5415',
 '5412-5414,5416-5419',
 '55',
 '56',
 '561',
 '562',
 '61,62',
 '61',
 '62',
 '621',
 '622',
 '623',
 '624',
 '71,72',
 '71',
 '711-712',
 '713',
 '72',
 '721',
 '722',
 '81',
 '92',
 '..2',
 '..3',
 '..4',
 '11,21',
 '42,44-45',
 '22,48-49',
 '31-33,51',
 '..5',
 '..6',
 '..7',
 '..8',
 '..9',
 '..10']

In [17]:
code_map = {}
level_map = {}
for code in gdp_codes:
    if ('-' in code) & (code not in incl_groups):
        if ',' in code:
            first, second = re.search(r'(\d+),(\d+)', code).groups()
            if '-' in first:
                start, end = re.search(r'(\d+)-(\d+)',first).groups()
                for i in range(int(start), int(end)+1):
                    code_map[str(i).ljust(4,'0')] = code

                level_map[code] = len(str(start))
            else:
                code_map[first.ljust(4,'0')] = code

                level_map[code] = len(str(first))

            if '-' in second:
                start, end = re.search(r'(\d+)-(\d+)',second).groups()
                for i in range(int(start), int(end)+1):
                    code_map[str(i).ljust(4,'0')] = code
            else:
                code_map[second.ljust(4,'0')] = code
        elif '-' in code:
            start, end = re.search(r'(\d+)-(\d+)', code).groups()
            for i in range(int(start), int(end)+1):
                code_map[str(i).ljust(4,'0')] = code

            level_map[code] = len(str(start))
    elif (code not in incl_groups) and not re.search(r'^\.\.', code):
        code_map[code.ljust(4,'0')] = code

        level_map[code] = len(code)
    else:
        level_map[code] = 1

In [18]:
code_map

{'1100': '11',
 '1110': '111-112',
 '1120': '111-112',
 '1130': '113-115',
 '1140': '113-115',
 '1150': '113-115',
 '2100': '21',
 '2110': '211',
 '2120': '212',
 '2130': '213',
 '2200': '22',
 '2300': '23',
 '3100': '31-33',
 '3200': '31-33',
 '3300': '31-33',
 '3210': '321',
 '3270': '327',
 '3310': '331',
 '3320': '332',
 '3330': '333',
 '3340': '334',
 '3350': '335',
 '3361': '3361-3363',
 '3362': '3361-3363',
 '3363': '3361-3363',
 '3466': '3364-3466,3369',
 '3369': '3364-3466,3369',
 '3370': '337',
 '3390': '339',
 '3110': '311-312',
 '3120': '311-312',
 '3130': '313-314',
 '3140': '313-314',
 '3150': '315-316',
 '3160': '315-316',
 '3220': '322',
 '3230': '323',
 '3240': '324',
 '3250': '325',
 '3260': '326',
 '4200': '42',
 '4400': '44-45',
 '4500': '44-45',
 '4800': '48-49',
 '4900': '48-49',
 '4810': '481',
 '4820': '482',
 '4830': '483',
 '4840': '484',
 '4850': '485',
 '4860': '486',
 '4880': '487-488,492',
 '4920': '487-488,492',
 '4930': '493',
 '5100': '51',
 '5110': '511',
 '5120': '512',
 '5150': '515-517',
 '5160': '515-517',
 '5170': '515-517',
 '5180': '518-519',
 '5190': '518-519',
 '5200': '52',
 '5210': '521-522',
 '5220': '521-522',
 '5230': '523',
 '5240': '524',
 '5250': '525',
 '5300': '53',
 '5310': '531',
 '5320': '532-533',
 '5330': '532-533',
 '5400': '54',
 '5411': '5411',
 '5415': '5415',
 '5414': '5412-5414,5416-5419',
 '5416': '5412-5414,5416-5419',
 '5500': '55',
 '5600': '56',
 '5610': '561',
 '5620': '562',
 '6100': '61',
 '6200': '62',
 '6210': '621',
 '6220': '622',
 '6230': '623',
 '6240': '624',
 '7100': '71',
 '7110': '711-712',
 '7120': '711-712',
 '7130': '713',
 '7200': '72',
 '7210': '721',
 '7220': '722',
 '8100': '81',
 '9200': '92'}

In [19]:
gdp_df

,GeoFIPS,STATE/REGION,NAICS,NAICS_LDESC,2010,2011,2012,2013,2014,2015,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,BEA_GROUP
0,0,USA,..0,All industry total,15048971,15599732,16253970,16880683,17608138,18295019,...,19612102,20656516,21539982.0,21375281,23725645,26054614,27811517,29298013,30762099,False
1,0,USA,..1,Private industries,12939469,13461114,14092708,14665532,15332504,15951002,...,17156255,18097765,18909779.0,18663991,20917717,23128892,24712793,26001672,27315089,False
2,0,USA,11,"Agriculture, forestry, fishing and hunting",145743,179887,179457,215847,200581,182147,...,176840,177117,164214.0,164383,230723,294048,270441,269686,272014,False
3,0,USA,111-112,Farms,117043,151135,148752,184472,167051,146259,...,138733,136825,122630.0,120506,185707,247070,218198,215830,(NA),False
4,0,USA,113-115,"Forestry, fishing, and related activities",28700,28752,30705,31375,33530,35887,...,38107,40291,41585.0,43877,45016,46978,52243,53856,(NA),False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5519,98000,Far West,"42,44-45",Trade,308278.4,325108.5,339625.1,361511.2,383250.9,413295.3,...,446144.5,464800.5,498875.1,504690.9,565381.6,611575.1,628440.8,657298,698828.9,True
5520,98000,Far West,"22,48-49",Transportation and utilities,115404.6,119191.8,120827.7,127149,134774.8,145637.2,...,167468.5,178150.5,194474.2,179377.1,218434.1,252347.3,262218.6,274775.4,284104.3,True
5521,98000,Far West,"31-33,51",Manufacturing and information,498197.6,511966.6,534056.7,584463.1,611997.3,661048,...,746914.7,795999.3,851222.8,857093.7,957317.9,981167.3,1048514.6,1110039.6,(D),True
5522,98000,Far West,..5,Private goods-producing industries 2/,474702.6,488104.3,512454.5,538550.9,560094.7,576510.9,...,635041.3,684408.5,706602.5,676781.6,743641.4,789941.3,816175.6,832203.2,837042,False
5523,98000,Far West,..6,Private services-providing industries 3/,1860016,1943510.1,2041166.9,2146085.5,2261102.9,2417328,...,2693166.3,2853206.8,3048307.7,3061197.6,3452890.6,3713813.1,3965392.5,4225135.9,4466626.3,False

In [20]:
gdp_df_l = pd.melt(gdp_df,
                   id_vars=['GeoFIPS','STATE/REGION','NAICS','NAICS_LDESC','BEA_GROUP'],
                    value_vars=['2010','2011','2012','2013','2014','2015',
                                '2016','2017','2018','2019','2020','2021','2022','2023','2024','2025'],
                    var_name='YEAR',
                    value_name='GDP')

In [21]:
gdp_df_l['GDP'] = pd.to_numeric(gdp_df_l['GDP'], errors='coerce') * 1000000
gdp_df_l['LEVEL'] = gdp_df_l['NAICS'].replace(level_map)

/var/folders/6q/62m63jt13_79jxp668tbwsd80000gp/T/ipykernel_86112/621453802.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  gdp_df_l['LEVEL'] = gdp_df_l['NAICS'].replace(level_map)

In [22]:
region_list = ['New England', 'Mideast', 'Great Lakes', 'Plains', 
               'Southeast', 'Southwest', 'Rocky Mountain', 'Far West']

gdp_states = gdp_df_l[~gdp_df_l['STATE/REGION'].isin(region_list)]

In [23]:
gdp_states

,GeoFIPS,STATE/REGION,NAICS,NAICS_LDESC,BEA_GROUP,YEAR,GDP,LEVEL
0,0,USA,..0,All industry total,False,2010,1.504897e+13,1
1,0,USA,..1,Private industries,False,2010,1.293947e+13,1
2,0,USA,11,"Agriculture, forestry, fishing and hunting",False,2010,1.457430e+11,2
3,0,USA,111-112,Farms,False,2010,1.170430e+11,3
4,0,USA,113-115,"Forestry, fishing, and related activities",False,2010,2.870000e+10,3
...,...,...,...,...,...,...,...,...
87643,56000,WY,"42,44-45",Trade,True,2025,5.349000e+09,1
87644,56000,WY,"22,48-49",Transportation and utilities,True,2025,5.444100e+09,1
87645,56000,WY,"31-33,51",Manufacturing and information,True,2025,NaN,1
87646,56000,WY,..5,Private goods-producing industries 2/,False,2025,NaN,1
87647,56000,WY,..6,Private services-providing industries 3/,False,2025,NaN,1

## Loading Census Population Data

In [24]:
pop_df = pd.read_csv('../data/population_est.csv')

In [25]:
pop_df = pd.melt(pop_df,
    id_vars=['STATE'],
    value_vars=['2010','2011','2012','2013','2014','2015','2016','2017',
               '2018','2019','2020','2021','2022','2023','2024','2025'],
    var_name='YEAR',
    value_name='EST_POP')

In [26]:
pop_df['STATE/REGION'] = pop_df['STATE'].replace('United States','USA').replace(state_abbr)
pop_df = pop_df.drop(columns=['STATE'])

In [27]:
pop_df

     YEAR    EST_POP STATE/REGION
0    2010    4785514           AL
1    2010     713982           AK
2    2010    6407342           AZ
3    2010    2921998           AR
4    2010   37319550           CA
..    ...        ...          ...
827  2025    8001020           WA
828  2025    1766147           WV
829  2025    5972787           WI
830  2025     588753           WY
831  2025  341784857          USA

[832 rows x 3 columns]

## Cleaning and Transforming Census Imports

In [28]:
imports_df.head(5)

      STATE      VALUE   NAICS       NAICS_LDESC  YEAR
92722     -  333889708    1122             SWINE  2013
92723     -  333889708   11221             SWINE  2013
92724     -  333889708  112210             SWINE  2013
92725     -   56965631    1123  POULTRY AND EGGS  2013
92726     -   56965631   1123X  POULTRY AND EGGS  2013

In [29]:
imports_df['STATE'] = imports_df['STATE'].replace('-','USA')

In [30]:
imports_df['NAICS'].unique()

array(['1122', '11221', '112210', '1123', '1123X', '1123XX', '1124',
       '11241', '112410', '11242', '112420', '1125', '11251', '112511',
       '112512', '1129', '11291', '112910', '11292', '112920', '11293',
       '112930', '11299', '112990', '113', '1132', '11321', '113210',
       '1133', '11331', '113310', '114', '1141', '11411', '114111',
       '114112', '114119', '21', '211', '2111', '21111', '211111',
       '211112', '212', '2121', '21211', '212111', '212112', '212113',
       '2122', '21221', '212210', '21222', '212221', '212222', '21223',
       '212231', '212234', '21229', '212291', '212299', '2123', '21231',
       '212311', '212312', '212319', '21232', '212321', '212322',
       '212324', '212325', '21239', '212391', '212392', '212393',
       '212399', '31', '31-33', '311', '3111', '31111', '311111',
       '311119', '3112', '31121', '311211', '311212', '311213', '31122',
       '311221', '311224', '311225', '31123', '311230', '3113', '31131',
       '31131X', '31134', '311340', '31135', '31135X', '3114', '31141',
       '311411', '311412', '31142', '311421', '311422', '311423', '3115',
       '31151', '311511', '311512', '311513', '311514', '31152', '311520',
       '3116', '31161', '311611', '311612', '311613', '311615', '3117',
       '31171', '311710', '3118', '31181', '31181X', '31182', '311824',
       '3119', '31191', '311911', '311919', '31192', '311920', '31193',
       '311930', '31194', '311941', '311942', '31199', '311991', '311999',
       '312', '3121', '31211', '312111', '312112', '312113', '31212',
       '312120', '31213', '312130', '31214', '312140', '3122', '31223',
       '312230', '313', '3131', '31311', '313110', '3132', '31321',
       '313210', '31322', '313220', '31323', '313230', '31324', '313240',
       '3133', '31332', '313320', '314', '3141', '31411', '314110',
       '31412', '314120', '3149', '31491', '314910', '31499', '314994',
       '314999', '315', '3151', '31511', '315110', '31519', '315190',
       '3152', '31522', '315220', '31524', '315240', '31528', '315280',
       '3159', '31599', '315990', '316', '3161', '31611', '316110',
       '3162', '31621', '316210', '3169', '31699', '316992', '316998',
       '32', '321', '3211', '32111', '321113', '321114', '3212', '32121',
       '321211', '321212', '321213', '321214', '321219', '3219', '32191',
       '321911', '321918', '32192', '321920', '32199', '321991', '321992',
       '321999', '322', '3221', '32211', '322110', '32212', '322121',
       '322122', '32213', '322130', '3222', '32221', '322211', '322212',
       '322219', '32222', '322220', '32223', '322230', '32229', '322291',
       '322299', '323', '3231', '32311', '323111', '323117', '32312',
       '323120', '324', '3241', '32411', '324110', '32412', '324121',
       '324122', '32419', '324191', '324199', '325', '3251', '32511',
       '325110', '32512', '325120', '32513', '325130', '32518', '325180',
       '32519', '325193', '325194', '325199', '3252', '32521', '325211',
       '325212', '32522', '325220', '3253', '32531', '325311', '325312',
       '32532', '325320', '3254', '32541', '325411', '325412', '325413',
       '325414', '3255', '32551', '325510', '32552', '325520', '3256',
       '32561', '325611', '325612', '325613', '32562', '325620', '3259',
       '32591', '325910', '32592', '325920', '32599', '325992', '325998',
       '326', '3261', '32611', '326111', '326113', '32612', '326121',
       '326122', '32616', '326160', '32619', '326191', '326199', '3262',
       '32621', '326211', '326212', '32622', '326220', '32629', '326291',
       '326299', '327', '3271', '32711', '327110', '32712', '327120',
       '3272', '32721', '327211', '327212', '327213', '327215', '3273',
       '32731', '327310', '32732', '327320', '32733', '327331', '32739',
       '327390', '3274', '32741', '327410', '32742', '327420', '3279',
       '32791', '327910', '32799', '327991', '327992', '327993', '327999',
       '33', '331', '3311', '33111', '331110', '3312', '33121', '331210',
       '33122', '331221', '331222', '3313', '33131', '331313', '331314',
       '331315', '331318', '3314', '33141', '331410', '33142', '331420',
       '33149', '331491', '331492', '3315', '33151', '331511', '331513',
       '33152', '331523', '331529', '332', '3321', '33211', '332111',
       '332112', '332119', '3322', '33221', '332215', '332216', '3323',
       '33231', '332311', '332312', '332313', '33232', '332321', '332322',
       '332323', '3324', '33241', '332410', '33242', '332420', '33243',
       '332431', '332439', '3325', '33251', '332510', '3326', '33261',
       '332613', '332618', '3327', '33272', '332722', '3329', '33291',
       '332911', '332912', '332913', '332919', '33299', '332991',
       '332992', '332993', '332994', '332999', '333', '3331', '33311',
       '333111', '333112', '33312', '333120', '33313', '333131', '333132',
       '3332', '33324', '333241', '333242', '333243', '333244', '333249',
       '3333', '33331', '333314', '333316', '333318', '3334', '33341',
       '333413', '333414', '333415', '3335', '33351', '-', '333511',
       '333514', '333515', '333517', '333519', '3336', '33361', '333611',
       '333612', '333613', '333618', '3339', '33391', '333911', '333912',
       '333913', '33392', '333921', '333922', '333923', '333924', '33399',
       '333991', '333992', '333993', '333994', '333995', '333996',
       '333997', '333999', '334', '3341', '33411', '334111', '334112',
       '334118', '3342', '33421', '334210', '33422', '334220', '33429',
       '334290', '3343', '33431', '334310', '3344', '33441', '334412',
       '334413', '334416', '334417', '334418', '334419', '3345', '33451',
       '334510', '334511', '334512', '334513', '334514', '334515',
       '334516', '334517', '334519', '3346', '33461', '334613', '334614',
       '335', '3351', '33511', '335110', '33512', '335121', '335122',
       '335129', '3352', '33521', '335210', '33522', '335221', '335222',
       '335224', '335228', '3353', '33531', '335311', '335312', '335313',
       '335314', '3359', '33591', '335911', '335912', '33592', '335921',
       '335929', '33593', '335931', '335932', '33599', '335991', '335999',
       '336', '3361', '33611', '336111', '336112', '33612', '336120',
       '3362', '33621', '336211', '336212', '336213', '336214', '3363',
       '33631', '336310', '33632', '336320', '33633', '336330', '33634',
       '336340', '33635', '336350', '33636', '336360', '33637', '336370',
       '33639', '336390', '3364', '33641', '336411', '336412', '336413',
       '336414', '336415', '336419', '3365', '33651', '336510', '3366',
       '33661', '336611', '336612', '3369', '33699', '336991', '336992',
       '336999', '337', '3371', '33711', '337110', '33712', '337121',
       '337122', '337124', '337125', '337127', '3372', '33721', '337211',
       '337212', '337214', '337215', '3379', '33791', '337910', '33792',
       '337920', '339', '3391', '33911', '339112', '339113', '339114',
       '339115', '339116', '3399', '33991', '339910', '33992', '339920',
       '33993', '339930', '33994', '11', '111', '1111', '339940', '33995',
       '339950', '33999', '339991', '339992', '339993', '339994',
       '339995', '339999', '91', '910', '9100', '91000', '910000', '93',
       '930', '9300', '93000', '930000', '98', '980', '9800', '98000',
       '980000', '99', '990', '9900', '99000', '990000', '11111',
       '111110', '11112', '111120', '11113', '111130', '11114', '111140',
       '11115', '111150', '11116', '111160', '11119', '111199', '1112',
       '11121', '111211', '111219', '1113', '11131', '111310', '11132',
       '111320', '11133', '111331', '111332', '111333', '111334',
       '111335', '111339', '1114', '11141', '111411', '11142', '111421',
       '111422', '1119', '11191', '111910', '11192', '111920', '11193',
       '111930', '11194', '111940', '11199', '111991', '111992', '111998',
       '112', '1121', '11211', '11211X', '115', '1151', '1152', '51',
       '511', '5112', '92', '920', '9200'], dtype=object)

In [31]:
imports_df['NAICS'] = imports_df['NAICS'].str.replace('0','').str.replace('X','')

imports_df['NAICS_pad'] = imports_df['NAICS'].str[:4].str.ljust(4,'0')
import_codes = imports_df['NAICS_pad'].unique().tolist()

imports_df = imports_df.drop_duplicates(subset=['STATE','VALUE','YEAR','NAICS'])

In [32]:
imports_df['LEVEL'] = imports_df['NAICS'].str.len()

imports_df.loc[imports_df['NAICS'] == '31-33', 'LEVEL'] = 2

In [33]:
for code in import_codes:
    if code == '-000':
        code_map[code] = '..0'
    elif code == '31-3':
        code_map[code] = '31-33'
    elif code not in code_map.keys():
        code_map[code] = 'NA'
        for i in range(4):
            pad_code = code[:-1] + '0' * (i + 1)
            if pad_code in code_map.keys():
                code_map[code] = code_map[pad_code]
                break

In [34]:
imports_df['GDP_CODE'] = imports_df['NAICS_pad'].replace(code_map)

In [35]:
imports_df = imports_df.drop(columns=['NAICS_pad']).rename(columns={
    'STATE':'STATE/REGION',
    'VALUE':'IMPORT_VAL',
    'NAICS':'IMP_NAICS',
    'NAICS_LDESC':'IMP_NAICS_DESC',
    'LEVEL':'IMP_LEVEL'})

In [36]:
imports_df

,STATE/REGION,IMPORT_VAL,IMP_NAICS,IMP_NAICS_DESC,YEAR,IMP_LEVEL,GDP_CODE
92722,USA,333889708,1122,SWINE,2013,4,111-112
92723,USA,333889708,11221,SWINE,2013,5,111-112
92725,USA,56965631,1123,POULTRY AND EGGS,2013,4,111-112
92728,USA,14396070,1124,"SHEEP, GOATS AND FINE ANIMAL HAIR",2013,4,111-112
92729,USA,10686925,11241,SHEEP AND WOOL,2013,5,111-112
...,...,...,...,...,...,...,...
1534263,WA,315932005,99,OTHER SPECIAL CLASSIFICATION PROVISIONS,2025,2,NA
1534264,WI,239760200,99,OTHER SPECIAL CLASSIFICATION PROVISIONS,2025,2,NA
1534265,WV,8890626,99,OTHER SPECIAL CLASSIFICATION PROVISIONS,2025,2,NA
1534266,WY,15238401,99,OTHER SPECIAL CLASSIFICATION PROVISIONS,2025,2,NA
1534267,XX,30113252331,99,OTHER SPECIAL CLASSIFICATION PROVISIONS,2025,2,NA

## Cleaning and Transforming Census Exports

In [37]:
exports_df.head(5)

      STATE        VALUE   NAICS                         NAICS_LDESC  YEAR
92265     -  79737309998      11  AGRICULTURE AND LIVESTOCK PRODUCTS  2013
92266     -  68935141909     111               AGRICULTURAL PRODUCTS  2013
92267     -  41576840935    1111                 OILSEEDS AND GRAINS  2013
92268     -  21605835043   11111                            SOYBEANS  2013
92269     -  21605835043  111110                            SOYBEANS  2013

In [38]:
exports_df['STATE'] = exports_df['STATE'].replace('-','USA')

In [39]:
exports_df['NAICS'].unique()

array(['11', '111', '1111', '11111', '111110', '11112', '11114', '111120',
       '11113', '111130', '111140', '11115', '111150', '11116', '111160',
       '11119', '111199', '1112', '11121', '111211', '111219', '1113',
       '11131', '111310', '11132', '111320', '11133', '111331', '111335',
       '111332', '111333', '111334', '111339', '1114', '11141', '111411',
       '11142', '111421', '111422', '1119', '11191', '111910', '11192',
       '111920', '11193', '111930', '11194', '111940', '11199', '111991',
       '111992', '111998', '112', '1121', '11221', '11211', '11211X',
       '1122', '112210', '1123', '1123X', '1123XX', '1124', '11241',
       '112410', '11242', '112420', '1125', '11251', '112511', '112512',
       '1129', '11291', '112910', '11292', '112920', '11293', '112930',
       '11299', '112990', '113', '1132', '11321', '113210', '1133',
       '11331', '113310', '114', '1141', '11411', '114111', '114112',
       '114119', '21', '211', '2111', '21111', '211111', '211112', '212',
       '2121', '21211', '212111', '212112', '212113', '2122', '21221',
       '212210', '21222', '212221', '212222', '21223', '212231', '212234',
       '21229', '212291', '212299', '2123', '21231', '212311', '212312',
       '212319', '21232', '212321', '212322', '212324', '212325', '21239',
       '212391', '212392', '212393', '212399', '31', '31-33', '311',
       '3111', '31111', '311111', '311119', '3112', '31121', '311211',
       '311221', '311212', '311213', '31122', '311224', '311225', '31123',
       '311230', '3113', '31131', '31131X', '31135X', '31134', '311340',
       '31135', '3114', '31141', '311411', '311412', '31142', '311421',
       '311422', '311423', '3115', '31151', '311511', '311512', '311513',
       '311514', '31152', '311520', '3116', '31161', '311611', '311613',
       '311615', '3117', '31171', '311710', '3118', '31181', '31181X',
       '31182', '311824', '3119', '31191', '311911', '311919', '31192',
       '311920', '31193', '311930', '31194', '311941', '32731', '327213',
       '327215', '3273', '327310', '32732', '327320', '32733', '327331',
       '32739', '327390', '3274', '32741', '327410', '32742', '327420',
       '3279', '32791', '327910', '32799', '327991', '327992', '327993',
       '327999', '33', '331', '3311', '33111', '331110', '3312', '33121',
       '331210', '33122', '331221', '331222', '3313', '33131', '331313',
       '331314', '331315', '331318', '3314', '33141', '331410', '33142',
       '331420', '33149', '331491', '331492', '3315', '33151', '331511',
       '331513', '33152', '331523', '332111', '332', '3321', '33211',
       '332112', '332119', '3322', '33221', '332215', '332216', '3323',
       '33231', '332311', '332312', '332313', '33232', '332321', '332322',
       '332323', '3324', '33241', '332410', '33242', '332420', '33243',
       '332431', '332439', '3325', '33251', '332510', '3326', '33261',
       '332613', '332618', '3327', '33272', '332722', '3329', '33291',
       '332911', '332912', '332913', '332919', '33299', '332991',
       '332992', '332993', '332994', '332999', '333', '3331', '33311',
       '333111', '333112', '333131', '33312', '333120', '33313', '333132',
       '3332', '33324', '333241', '333242', '333243', '333244', '333249',
       '3333', '33331', '333314', '333316', '333318', '3334', '33341',
       '333413', '333414', '333415', '3335', '33351', '333511', '333514',
       '333515', '333517', '333519', '3336', '33361', '333611', '333612',
       '333613', '333618', '3339', '33391', '333911', '333912', '333913',
       '33392', '333921', '333922', '333923', '333924', '33399', '333991',
       '333992', '333996', '333993', '333994', '333995', '333997',
       '333999', '334111', '334', '3341', '33411', '334112', '334118',
       '3342', '33421', '334210', '33422', '334220', '33429', '334290',
       '3343', '33431', '334310', '3344', '33441', '334412', '334413',
       '334416', '334417', '334418', '334419', '3345', '33451', '334510',
       '334511', '334512', '334513', '334514', '334515', '334516',
       '334517', '334519', '3346', '33461', '334613', '33511', '334614',
       '335', '3351', '335110', '33512', '335121', '335122', '335129',
       '3352', '33521', '335210', '33522', '335221', '335222', '335224',
       '339950', '33999', '339991', '339992', '339993', '339994',
       '339999', '91', '910', '9100', '91000', '910000', '93', '930',
       '9300', '93000', '930000', '98', '980', '9800', '98000', '980000',
       '99', '990', '9900', '99000', '990000', '335312', '-', '335228',
       '3353', '33531', '335311', '335313', '335314', '3359', '33591',
       '335911', '335912', '33592', '335921', '335929', '33593', '335931',
       '335932', '33599', '335991', '335999', '336', '3361', '33611',
       '336111', '336112', '33612', '336120', '3362', '33621', '336211',
       '3363', '336212', '336213', '336214', '33631', '336310', '33632',
       '336320', '33633', '336330', '33634', '336340', '33635', '336350',
       '33636', '336360', '33637', '336370', '33639', '336390', '3364',
       '33641', '336411', '336412', '336419', '336413', '336414',
       '336415', '33641X', '3365', '33651', '336510', '3366', '33661',
       '336611', '336612', '3369', '33699', '336991', '336992', '336999',
       '337', '3371', '33711', '337110', '33712', '337121', '337122',
       '337124', '337125', '337127', '337214', '3372', '33721', '337211',
       '337215', '3379', '33791', '337910', '33792', '337920', '339',
       '3391', '33911', '339112', '339113', '339114', '339115', '339116',
       '3399', '33991', '339910', '33992', '339920', '33993', '339930',
       '33994', '339940', '33995', '311999', '311942', '31199', '311991',
       '312111', '312', '3121', '31211', '312112', '312113', '31212',
       '312120', '31213', '312130', '31214', '312140', '3122', '31223',
       '312230', '313', '3131', '31311', '313110', '3132', '31321',
       '313210', '31322', '313220', '31323', '313230', '31324', '313240',
       '3133', '31332', '313320', '314', '3141', '31411', '314110',
       '31412', '314120', '3149', '31491', '314910', '31499', '314994',
       '314999', '315', '3151', '31511', '315110', '31519', '315190',
       '3152', '31522', '315220', '31524', '315240', '31528', '315280',
       '3159', '31599', '315990', '316', '3161', '31611', '316110',
       '3162', '31621', '316210', '3169', '31699', '316992', '316998',
       '32', '321', '3211', '32111', '321113', '321114', '3212', '32121',
       '321211', '321212', '321213', '321219', '3219', '32191', '321911',
       '321918', '32192', '321920', '32199', '321991', '321992', '321999',
       '322', '3221', '32211', '322110', '32212', '322121', '322122',
       '32213', '322130', '3222', '32221', '322211', '322212', '322219',
       '322230', '32222', '322220', '32223', '32229', '322291', '322299',
       '323', '3231', '32311', '323111', '323117', '32312', '323120',
       '324', '3241', '32411', '324110', '32412', '324121', '324122',
       '32419', '324199', '325', '3251', '32511', '325110', '32512',
       '325120', '32513', '325130', '32518', '325180', '32519', '325193',
       '325194', '325199', '3252', '32521', '325211', '325212', '32522',
       '325220', '325312', '3253', '32531', '325311', '32532', '325320',
       '3254', '32541', '325411', '325412', '32551', '325413', '325414',
       '3255', '325510', '32552', '325520', '3256', '32561', '325611',
       '325612', '325613', '32562', '325620', '3259', '32591', '325910',
       '32592', '325920', '32599', '325992', '325998', '326', '3261',
       '32611', '326111', '326113', '32612', '326121', '326122', '32616',
       '326160', '3262', '32619', '326191', '326199', '32621', '326211',
       '326212', '32622', '326220', '32629', '326291', '326299', '327',
       '3271', '32711', '327110', '32712', '327120', '3272', '32721',
       '327211', '327212', '115', '1152', '51', '511', '5112', '92',
       '920', '9200'], dtype=object)

In [40]:
exports_df['NAICS'] = exports_df['NAICS'].str.replace('0','').str.replace('X','')

exports_df['NAICS_pad'] = exports_df['NAICS'].str[:4].str.ljust(4,'0')
export_codes = exports_df['NAICS_pad'].unique().tolist()

exports_df = exports_df.drop_duplicates(subset=['STATE','VALUE','YEAR','NAICS'])

In [41]:
exports_df['LEVEL'] = exports_df['NAICS'].str.len()

exports_df.loc[exports_df['NAICS'] == '31-33', 'LEVEL'] = 2

In [42]:
for code in export_codes:
    if code == '-000':
        code_map[code] = '..0'
    elif code == '31-3':
        code_map[code] = '31-33'
    elif code not in code_map.keys():
        code_map[code] = 'NA'
        for i in range(4):
            pad_code = code[:-1] + '0' * (i + 1)
            if pad_code in code_map.keys():
                code_map[code] = code_map[pad_code]
                break

In [43]:
exports_df['GDP_CODE'] = exports_df['NAICS_pad'].replace(code_map)

In [44]:
exports_df = exports_df.drop(columns=['NAICS_pad']).rename(columns={
    'STATE':'STATE/REGION',
    'VALUE':'EXPORT_VAL',
    'NAICS':'EXP_NAICS',
    'NAICS_LDESC':'EXP_NAICS_DESC',
    'LEVEL':'EXP_LEVEL'})

In [45]:
exports_df

,STATE/REGION,EXPORT_VAL,EXP_NAICS,EXP_NAICS_DESC,YEAR,EXP_LEVEL,GDP_CODE
92265,USA,79737309998,11,AGRICULTURE AND LIVESTOCK PRODUCTS,2013,2,11
92266,USA,68935141909,111,AGRICULTURAL PRODUCTS,2013,3,111-112
92267,USA,41576840935,1111,OILSEEDS AND GRAINS,2013,4,111-112
92268,USA,21605835043,11111,SOYBEANS,2013,5,111-112
92270,USA,458793743,11112,OILSEEDS (EXCEPT SOYBEAN),2013,5,111-112
...,...,...,...,...,...,...,...
1511797,XX,535298644,3322,CUTLERY AND HANDTOOLS,2025,4,332
1511798,XX,165509591,3323,ARCHITECTURAL AND STRUCTURAL METALS,2025,4,332
1511799,XX,122015935,3324,"BOILERS, TANKS, AND SHIPPING CONTAINERS",2025,4,332
1511800,XX,546389952,3325,HARDWARE,2025,4,332
1511801,XX,84839473036,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2025,1,..0

## Combining & Exporting Datasets

In [46]:
import_join = (imports_df.groupby(['GDP_CODE','YEAR','STATE/REGION'])['IMPORT_VAL']
    .sum()
    .reset_index()
    .rename(columns={'IMPORT_VAL':'GDP_IMP_SUM'}))
export_join = (exports_df.groupby(['GDP_CODE','YEAR','STATE/REGION'])['EXPORT_VAL']
    .sum()
    .reset_index()
    .rename(columns={'EXPORT_VAL':'GDP_EXP_SUM'}))

In [47]:
gdp_imports = import_join.merge(
    gdp_states, 
    left_on=['STATE/REGION','YEAR','GDP_CODE'],
    right_on=['STATE/REGION','YEAR','NAICS'],
    how='inner').drop(columns=['GDP_CODE']).merge(
    pop_df,
    on=['STATE/REGION','YEAR'],
    how='inner'
    )
gdp_exports = export_join.merge(
    gdp_states,
    left_on=['STATE/REGION','YEAR','GDP_CODE'],
    right_on=['STATE/REGION','YEAR','NAICS'],
    how='inner').drop(columns=['GDP_CODE']).merge(
    pop_df,
    on=['STATE/REGION','YEAR'],
    how='inner'
    )

In [48]:
gdp_states = gdp_states.merge(
    pop_df,
    on=['STATE/REGION','YEAR'],
    how='left'
)

In [49]:
imports_df.to_csv('../outputs/census_imports.csv',index=False)
exports_df.to_csv('../outputs/census_exports.csv',index=False)

gdp_imports.to_csv('../outputs/gdp_imports.csv',index=False)
gdp_exports.to_csv('../outputs/gdp_exports.csv',index=False)

gdp_states.to_csv('../outputs/gdp_states.csv',index=False)

## EDA

In [52]:
imports_df[imports_df['IMP_LEVEL'] == 1]

,STATE/REGION,IMPORT_VAL,IMP_NAICS,IMP_NAICS_DESC,YEAR,IMP_LEVEL,GDP_CODE
93216,USA,2267986733622,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2013,1,..0
93494,AK,1480639894,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2013,1,..0
93495,AL,18940757351,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2013,1,..0
93496,AR,7621331792,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2013,1,..0
93497,AZ,19023999012,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2013,1,..0
...,...,...,...,...,...,...,...
1526474,WA,55455245600,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2025,1,..0
1526475,WI,36453529501,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2025,1,..0
1526476,WV,4885342168,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2025,1,..0
1526477,WY,987744111,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2025,1,..0
1526478,XX,30272605853,-,TOTAL FOR ALL NORTH AMERICAN INDUSTRY CLASSIFI...,2025,1,..0